Update flow to use workflow dispatch

diff --git a/.github/workflows/draft-release-publish.yml b/.github/workflows/draft-release-publish.yml
--- a/.github/workflows/draft-release-publish.yml
+++ b/.github/workflows/draft-release-publish.yml
@@ -1,15 +1,19 @@
 name: Create draft release
 
 on:
-  pull_request:
-    paths:
-      - VERSION
-    branches:
-      - main
+  workflow_dispatch:
+    inputs:
+      version:
+        description: "The version you want to release in the format X.Y.Z"
+        required: true
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
   cancel-in-progress: true
+
+permissions:
+  contents: write
+  pull-requests: write
 
 jobs:
   publish-draft-release:
@@ -20,28 +24,53 @@ jobs:
       ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
       ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
     steps:
+      - name: Validate version format
+        id: validate_version
+        run: |
+          if [[ ! "${{ github.event.inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Invalid version format. Please provide a version in the format X.Y.Z where X, Y, and Z are numbers."
+            exit 1
+          fi
+          echo "Valid version: ${{ github.event.inputs.version }}"
+          echo "validated-version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
       - name: Checkout repository
         uses: actions/checkout@v4
       - name: Setup JDK
         uses: ./.github/actions/setup-java
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@v4
-      - name: Get version name
-        id: version
+      - name: Save validated version to file
         run: |
-          version_from_file=$(head -n 1 VERSION)
-          echo "release-version=$version_from_file" >> $GITHUB_OUTPUT
+          echo "${{ steps.validate_version.outputs.validated-version }}" > VERSION
       - name: RC version name
         id: version-suffix
         run: |
           version_suffix="-RC-$(date +'%Y%m%d%H%M')"
           echo "version-suffix=version_suffix" >> $GITHUB_OUTPUT
+      - name: Update changelog
+        uses: thomaseizinger/keep-a-changelog-new-release@v2
+        with:
+          tag: ${{ steps.validate_version.outputs.validated-version }}
       - name: Publish to Maven local
-        run: ./gradlew publishMavenPublicationToMavenLocal -PVERSION=${{ steps.version.outputs.release-version }} -PVERSION_SUFFIX=${{ steps.version-suffix.outputs.version-suffix }}
+        run: ./gradlew publishMavenPublicationToMavenLocal -PVERSION=${{ steps.validate_version.outputs.validated-version }} -PVERSION_SUFFIX=${{ steps.version-suffix.outputs.version-suffix }}
       - name: Publish to Maven Central
-        run: ./gradlew publishMavenPublicationToMavenCentralRepository -PVERSION=${{ steps.version.outputs.release-version }} -PVERSION_SUFFIX=${{ steps.version-suffix.outputs.version-suffix }} --no-configuration-cache
+        run: ./gradlew publishMavenPublicationToMavenCentralRepository -PVERSION=${{ steps.validate_version.outputs.validated-version }} -PVERSION_SUFFIX=${{ steps.version-suffix.outputs.version-suffix }} --no-configuration-cache
       - name: Upload AAR artifacts
         uses: actions/upload-artifact@v4
         with:
           name: aar-files
           path: "**/*.aar"
+      - name: Create Pull Request
+        uses: peter-evans/create-pull-request@v7
+        with:
+          commit-message: Create ${{ steps.validate_version.outputs.validated-version }}${{ steps.version-suffix.outputs.version-suffix }}
+          branch: release/${{ steps.validate_version.outputs.validated-version }}
+          title: Prepare release ${{ steps.validate_version.outputs.validated-version }}
+          base: main
+          body: |
+            Preparing for release ${{ steps.validate_version.outputs.validated-version }}
+            - Bumped version
+            - Updated changelog
+            - Generated RC build ${{ steps.validate_version.outputs.validated-version }}${{ steps.version-suffix.outputs.version-suffix }}
+          labels: |
+            release
